KGERP/Controllers/CompanyController.cs
using KGERP.Data.Models;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class CompanyController : Controller
    {
        private readonly ICompanyService companyService;
        public CompanyController(ICompanyService companyService)
        {
            this.companyService = companyService;
        }

        [SessionExpire]
        [HttpGet]
        public ActionResult Index(string searchText)
        {
            List<CompanyModel> companies = companyService.GetCompanies(searchText);
            List<CompanyModel> companiesWithImage = companies.Select(x => new CompanyModel
            {
                CompanyId = x.CompanyId,
                Name = x.Name,
                ShortName = x.ShortName,
                OrderNo = x.OrderNo,
                MushokNo = x.MushokNo,
                IsCompany = x.IsCompany,
                CompanyLogo = string.Format("{0}://{1}", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority) + "/Images/Logo/" + (string.IsNullOrEmpty(x.CompanyLogo) ? "logo.png" : x.CompanyLogo),
            }).ToList();
            return View(companiesWithImage);
        }

        [HttpGet]
        [SessionExpire]
        public ActionResult CreateOrEdit(int id)
        {
            CompanyModel company = companyService.GetCompany(id);
            company.CompanyLogo = string.Format("{0}://{1}", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority) + "/Images/Logo/" + (string.IsNullOrEmpty(company.CompanyLogo) ? "logo.png" : company.CompanyLogo);
            return View(company);
        }

        [HttpPost]
        [SessionExpire]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(CompanyModel model)
        {
            ModelState.Clear();
            string message = string.Empty;
            bool result = false;

            if (model.CompanyLogoUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(model.CompanyLogoUpload.FileName);
                string extension = Path.GetExtension(model.CompanyLogoUpload.FileName);
                fileName = fileName + "_" + DateTime.Now.ToString("yymmssfff") + extension;
                model.CompanyLogo = fileName;
                model.CompanyLogoUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Logo/"), fileName));
            }

            if (model.CompanyId <= 0)
            {
                result = companyService.SaveCompany(0, model);
            }
            else
            {
                result = companyService.SaveCompany(model.CompanyId, model);
            }
            if (result)
            {
                TempData["message"] = "Company Saved Successfully !";
            }
            else
            {
                TempData["message"] = "Company not Saved !";
            }
            return RedirectToAction("Index");
        }


    }

}

KGERP/Controllers/ConfigurationController.cs
using DocumentFormat.OpenXml.EMMA;
using KGERP.Data.Models;
using KGERP.Service.Configuration;
using KGERP.Service.Implementation;
using KGERP.Service.Implementation.CurrencyCon;

using KGERP.Service.Interface;

using KGERP.Utility;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Dynamic;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Pos.App.Controllers
{
    [SessionExpire]
    public class ConfigurationController : Controller
    {

        private HttpContext httpContext;
        private readonly ConfigurationService _service;
        private readonly ICompanyService _companyService;
     
        private readonly IVoucherTypeService voucherTypeService;
       
        public ConfigurationController(
            ICompanyService companyService,
            IVoucherTypeService voucherTypeService,
            ConfigurationService configurationService
            )
        {
            _service = configurationService;
            _companyService = companyService;
           
            this.voucherTypeService = voucherTypeService;
           
        }

        #region User Role Menuitem
        public async Task<ActionResult> UserMenuAssignment(int companyId)
        {
            VMUserMenuAssignment vmUserMenuAssignment = new VMUserMenuAssignment();
            vmUserMenuAssignment.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");

            return View(vmUserMenuAssignment);
        }
        [HttpPost]
        public async Task<ActionResult> UserMenuAssignment(VMUserMenuAssignment model)
        {
            VMUserMenuAssignment vmUserMenuAssignment = new VMUserMenuAssignment();
            vmUserMenuAssignment = await _service.UserMenuAssignmentGet(model);
            return View(vmUserMenuAssignment);
        }

        public JsonResult CompanyUserMenuEdit(int id, bool isActive)
        {
            VMUserMenuAssignment model = new VMUserMenuAssignment
            {
                IsActive = isActive,
                CompanyUserMenusId = id
            };
            CompanyUserMenu companyUserMenu = _service.CompanyUserMenuEdit(model);
            return Json(new { menuid = companyUserMenu.CompanyUserMenuId, updatedstatus = companyUserMenu.IsActive });
        }

        #endregion
        public async Task<ActionResult> AccountingCostCenter(int companyId)
        {
            VMUserMenu vmUserMenu;
            vmUserMenu = await Task.Run(() => _service.AccountingCostCenterGet(companyId));

            return View(vmUserMenu);
        }
        [HttpPost]
        public async Task<ActionResult> AccountingCostCenter(VMUserMenu model)
        {

            if (model.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.AccountingCostCenterAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.AccountingCostCenterEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.AccountingCostCenterDelete(model.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(AccountingCostCenter), new { companyId = model.CompanyFK });
        }

        #region User Menu
        public async Task<ActionResult> UserMenu()
        {
            VMUserMenu vmUserMenu;
            vmUserMenu = await Task.Run(() => _service.UserMenuGet());
            vmUserMenu.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");

            return View(vmUserMenu);
        }
        [HttpPost]
        public async Task<ActionResult> UserMenu(VMUserMenu model)
        {

            if (model.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.UserMenuAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.UserMenuEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.UserMenuDelete(model.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(UserMenu), new { companyId = model.CompanyFK });
        }


        #endregion

        #region User Submenu
        public async Task<ActionResult> UserSubMenu()
        {
            VMUserSubMenu vmUserSubMenu;
            vmUserSubMenu = await Task.Run(() => _service.UserSubMenuGet());
            vmUserSubMenu.UserMenuList = new SelectList(_service.CompanyMenusDropDownList(), "Value", "Text");
            vmUserSubMenu.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");

            return View(vmUserSubMenu);
        }
        [HttpPost]
        public async Task<ActionResult> UserSubMenu(VMUserSubMenu model)
        {
            if (model.ActionEum == ActionEnum.Add)
            {
                await _service.UserSubMenuAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                await _service.UserSubMenuEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                await _service.UserSubMenuDelete(model.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(UserSubMenu), new { companyId = model.CompanyFK });
        }
        #endregion

      

        public async Task<ActionResult> AccountingSignatory(int companyId)
        {

            VMAccountingSignatory vmAccountingSignatory = new VMAccountingSignatory();
            vmAccountingSignatory = await Task.Run(() => _service.GetAccountingSignatory(companyId));
            vmAccountingSignatory.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");
            return View(vmAccountingSignatory);
        }
        [HttpPost]
        public async Task<ActionResult> AccountingSignatory(VMAccountingSignatory vmAccountingSignatory)
        {

            if (vmAccountingSignatory.ActionEum == ActionEnum.Add)
            {


                await _service.AccountingSignatoryAdd(vmAccountingSignatory);
            }
            else if (vmAccountingSignatory.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.AccountingSignatoryEdit(vmAccountingSignatory);
            }
            else if (vmAccountingSignatory.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.AccountingSignatoryDelete(vmAccountingSignatory.SignatoryId);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(AccountingSignatory), new { companyId = vmAccountingSignatory.CompanyFK });
        }


        public async Task<ActionResult> Company()
        {

            VMCompany VMCompany = new VMCompany();
            VMCompany = await Task.Run(() => _service.GetCompany());
            //VMCompany.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");

            return View(VMCompany);
        }
        [HttpPost]
        public async Task<ActionResult> Company(VMCompany VMCompany)
        {

            if (VMCompany.ActionEum == ActionEnum.Add)
            {


                await _service.CompanyAdd(VMCompany);
            }
            //else if (VMCompany.ActionEum == ActionEnum.Edit)
            //{
            //    //Edit
            //    await _service.AccountingSignatoryEdit(VMCompany);
            //}
            //else if (VMCompany.ActionEum == ActionEnum.Delete)
            //{
            //    //Delete
            //    await _service.AccountingSignatoryDelete(VMCompany.SignatoryId);
            //}
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(Company));
        }


    }
}

KGERP/Views/Configuration/AccountingSignatory.cshtml
@{

    ViewData["Title"] = "Raw Materials Subcategory";
    Layout = "~/Views/Shared/_Layout.cshtml";


}
@model KGERP.Service.Configuration.VMAccountingSignatory
<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>
<section class="content-header">
    <h1>
        Account Signatory
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active"> Signatory </li>
    </ol>
</section>
@using (Html.BeginForm("AccountingSignatory", "Configuration", FormMethod.Post, new { id = "commonAccountingSignatoryFormId", @class = "formValidator", onreset = "resetDDL();" }))
{
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="box-danger">
                        <div class="box-header">
                            <h4>Add Signatory</h4>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            @Html.HiddenFor(model => model.SignatoryId, new { id = "hidSignatoryId" })
                            @Html.HiddenFor(model => model.ActionId, new { id = "ActionId" })
                            @Html.HiddenFor(model => model.CompanyFK, new { id = "CompanyFK" })
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Company Name:</label>
                                    @Html.DropDownListFor(model => model.CompanyFK, Model.CompanyList as SelectList, "---Select Company---", new { id = "ddlCompanyId", @class = "searchingDropdown form-control", required = "required" })
                                    @Html.ValidationMessageFor(model => model.CompanyFK, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Signatory Type:</label>
                                    @Html.TextBoxFor(model => model.SignatoryType, new { id = "txtSignatoryType", @class = "form-control", @placeholder = "Signatory Type" })
                                    @Html.ValidationMessageFor(model => model.SignatoryType, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Signatory Name:</label>
                                    @Html.TextBoxFor(model => model.SignatoryName, new { id = "txtSignatoryName", @class = "form-control", @placeholder = "Signatory Name" })
                                    @Html.ValidationMessageFor(model => model.SignatoryName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Order By:</label>
                                    @Html.TextBoxFor(model => model.OrderBy, new { id = "txtOrderBy", @class = "form-control", @placeholder = "Order By" })
                                    @Html.ValidationMessageFor(model => model.OrderBy, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-5">
                                    <button type="button" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Reset</button>
                                </div>
                                <div class="col-md-7">
                                    <button type="submit" id="btnSave" class="btn btn-primary btn-block"><i class='fa fa-edit'></i> Add</button>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                        </div>
                    </div>
                </div>
                <div class="box">
                    <div class="box-danger">
                        <div class="box-header">
                            <h4>Signatory List</h4>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="table-responsive col-md-12">
                                <table id="KgErpDataTable" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>SL</th>
                                            <th>Company Name</th>
                                            <th>Signatory Type</th>
                                            <th>Signatory Name</th>
                                            <th>Order By</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    @{int sl = 0;
                                    }
                                    <tbody>
                                        @foreach (var item in Model.DataList)
                                        {

                                        <tr>
                                            <td>@(++sl)</td>
                                            <td>
                                                <input type="hidden" id="CompanyFK_@item.SignatoryId" name="CompanyFK" value="@item.CompanyFK" />
                                                @item.CompanyName
                                            </td>
                                            <td id="tdSignatoryType_@item.SignatoryId">@item.SignatoryType</td>
                                            <td id="tdSignatoryName_@item.SignatoryId">@item.SignatoryName</td>
                                            <td id="tdOrderBy_@item.SignatoryId">@item.OrderBy</td>
                                            <td>
                                                <a id="@item.SignatoryId" onclick="makeEditble(this)" class="linkPointer" title="Edit"><i class="fa fa-pencil-square-o"></i></a>
                                                <a id="@item.SignatoryId" onclick="makeDeletable(@item.SignatoryId);" class="linkPointer" data-toggle="modal" data-target="#deleteModal" title="Delete"
                                                   data-placement="top">
                                                    <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                                </a>

                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="box-footer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

}

@using (Html.BeginForm("AccountingSignatory", "Configuration", FormMethod.Post, new { id = "commonAccountingSagnatoryDeleteFormId", @class = "formValidator", onreset = "resetDDL();" }))
{
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @Html.HiddenFor(model => model.SignatoryId, new { id = "SignatoryIdDelete" })
    @Html.HiddenFor(model => model.ActionId, new { id = "ActionIdDelete" })
    @Html.HiddenFor(model => model.CompanyFK, new { id = "CompanyFKDelete" })

    <div class="modal fade" id="deleteModal" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" onclick="resetForm()" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        &times;
                    </button>
                    <h5 class="modal-title"><b>Signatory Delete</b></h5>
                </div>
                <div class="modal-body">
                    <div style="text-align:center">
                        <h3>Are you sure to delete?</h3>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnClose" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnDelete" class="deleteId btn btn-primary"><i class="glyphicon glyphicon-check"></i> Confirm</button>
                </div>
            </div>
        </div>
    </div>
}

    @section scripts {
        <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();

             
        });
        function makeEditble(elem) {
            if (elem !== null) {
                var rowId = elem.id;
                $('#hidSignatoryId').val(rowId);
                $('#ActionId').val(2);
                $('#btnSave').html("<i class='fa fa-edit'></i>&nbsp;Update");
                $('#ddlCompanyId').val($('#CompanyFK_' + rowId).val()).change();
                $('#txtSignatoryType').val($('#tdSignatoryType_' + rowId).text().trim());
                $('#txtSignatoryName').val($('#tdSignatoryName_' + rowId).text().trim());
                $('#txtOrderBy').val($('#tdOrderBy_' + rowId).text().trim());

                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        }
        function makeDeletable(id) {
            if (id !== null) {
                $('#SignatoryIdDelete').val(id);
                $('#ActionIdDelete').val(3);
            }
        }
        function resetForm() {
            $('#commonAccountingSignatoryFormId')[0].reset();
            $('#btnSave').html("<i class='fa fa-edit'></i>&nbsp;Add");
        }
        </script>
    }

KGERP/Views/Configuration/CommonPackingCategory.cshtml
@using KG.Core.Services

@{
    ViewData["Title"] = "Packing Category";
    Layout = "~/Views/Shared/_Layout.cshtml";


}
@model KGERP.Service.Configuration.VMCommonProductCategory
<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>
<section class="content-header">
    <h1>
        Packing Category
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">Packing Category</li>
    </ol>
</section>
@using (Html.BeginForm("CommonPackingCategory", "Configuration", FormMethod.Post, new { id = "commonFinishProductCategoryFormId", @class = "formValidator", onreset = "resetDDL();" }))
{
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-3">
                    <div class="box">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="box-danger">
                            <div class="box-header">
                                <h4>Add Packing Category</h4>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                @Html.HiddenFor(model => model.ID, new { id = "productCategoryId" })
                                @Html.HiddenFor(model => model.ActionId, new { id = "ActionId" })
                                @Html.HiddenFor(model => model.CompanyFK, new { id = "CompanyFK" })

                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.Name, new { id = "txtProductCategoryName", @class = "form-control input-sm", @placeholder = "Category Name", required = "true", })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <div class="col-md-5">
                                        <button type="button" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Reset</button>
                                    </div>
                                    <div class="col-md-7">
                                        <button type="submit" id="btnSave" class="btn btn-primary btn-block"><i class='fa fa-edit'></i> Add</button>

                                    </div>

                                </div>
                            </div>
                            <div class="box-footer">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="box">

                        <div class="box-danger">
                            <div class="box-header">
                                <h4>Packing Category List</h4>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="table-responsive col-md-12">
                                    <table id="KgErpDataTable" class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>SL</th>
                                                <th>Name</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        @{int sl = 0;
                                        }
                                        <tbody>
                                            @foreach (var item in Model.DataList)
                                            {

                                                <tr>
                                                    <td>@(++sl)</td>
                                                    <td id="tdProductCategoryName_@item.ID">@item.Name</td>

                                                    <td>

                                                        <a id="@item.ID" onclick="makeEditble(this);" class="linkPointer" title="Edit"><i class="fa fa-pencil-square-o"></i></a>

                                                        <a id="@item.ID" onclick="makeDeletable(@item.ID);" class="linkPointer" data-toggle="modal" data-target="#productCategoryDeleteModal" title="Delete"
                                                           data-placement="top">
                                                            <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                                        </a>

                                                        <a href="~/Configuration/CommonPackingSubCategory?companyId=@item.CompanyFK&categoryId=@item.ID" class="btn btn-success btn-sm">Packing Subcategory</a>
                                                        <a href="~/Configuration/CommonPackingMaterials?companyId=@item.CompanyFK&categoryId=@item.ID" class="btn btn-warning btn-sm">Packing Materials</a>

                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                            <div class="box-footer">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>


}


@using (Html.BeginForm("CommonRawProductCategory", "Configuration", FormMethod.Post, new { id = "commonFinishProductCategoryDeleteFormId", @class = "formValidator", onreset = "resetDDL();" }))
{
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @Html.HiddenFor(model => model.ID, new { Value = "", id = "productCategoryIdDelete" })
    @Html.HiddenFor(model => model.ActionId, new { Value = "", id = "ActionIdDelete" })
    @Html.HiddenFor(model => model.CompanyFK, new { Value = "", id = "CompanyFKDelete" })

    <div class="modal fade" id="productCategoryDeleteModal" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" onclick="resetForm()" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        &times;
                    </button>
                    <h5 class="modal-title"><b>Packing Category Delete</b></h5>

                </div>
                <div class="modal-body">
                    <div style="text-align:center">
                        <h3>Are you sure to delete this Packing category?</h3>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" id="btnClose" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnDelete" class="deleteId btn btn-primary"><i class="glyphicon glyphicon-check"></i> Confirm</button>
                </div>
            </div>
        </div>
    </div>
}



@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();

        });

        function makeEditble(elem) {
            if (elem !== null) {
                var rowId = elem.id;
                $('#productCategoryId').val(rowId);
                $('#ActionId').val(2);
                $('#btnSave').html("<i class='fa fa-edit'></i>&nbsp;Update");
                $('#txtProductCategoryName').val($('#tdProductCategoryName_' + rowId).text().trim());
                window.scrollTo({ top: 0, behavior: 'smooth' });

            }
        }

        function makeDeletable(id) {
            if (id !== null) {
                $('#productCategoryIdDelete').val(id);
                $('#ActionIdDelete').val(3);
                $('#CompanyFKDelete').val("@Model.CompanyFK");

            }
        }
        function resetForm() {
            $('#commonFinishProductCategoryFormId')[0].reset();
            $('#btnSave').html("<i class='fa fa-edit'></i>&nbsp;Add");

        }

    </script>
}