KGERP/Controllers/AccountHeadsController.cs
using KGERP.Service.Interface;
using KGERP.Utility;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class AccountHeadsController : BaseController
    {
        private readonly IAccountHeadService accountHeadService;

        public AccountHeadsController(IAccountHeadService accountHeadService)
        {
            this.accountHeadService = accountHeadService;
        }

        // GET: AccountHeads
        //public ActionResult Index(int? Page_No, string searchText)
        //{
        //    if (GetCompanyId() > 0)
        //    {
        //        Session["CompanyId"] = GetCompanyId();
        //    }
        //    searchText = searchText ?? "";
        //    List<AccountHeadModel> accountHeads = accountHeadService.GetAccountHeads(Convert.ToInt32(Session["CompanyId"]), searchText);
        //    int Size_Of_Page = 10;
        //    int No_Of_Page = (Page_No ?? 1);
        //    return View(accountHeads.ToPagedList(No_Of_Page, Size_Of_Page));
        //}


        // GET: AccountHeads/Create
        //[HttpGet]
        //[SessionExpire]
        //public ActionResult CreateOrEdit(long id)
        //{
        //    string c = Request.QueryString["companyId"];
        //    int companyId = Convert.ToInt32(Session["CompanyId"]);
        //    AccountHeadViewModel vm = new AccountHeadViewModel();
        //    vm.AccountHead = accountHeadService.GetAccountHead(id);
        //    vm.AccountHead.CompanyId = companyId;
        //    vm.ParentHeads = accountHeadService.GetParentAccountHeadSelectModelByCompany(companyId);
        //    return View(vm);
        //}

        // POST: AccountHeads/Create 
        //[HttpPost]
        //[ValidateAntiForgeryToken]

        //public ActionResult CreateOrEdit(AccountHeadViewModel vm)
        //{
        //    bool result = false;
        //    if (vm.AccountHead.AccountHeadId <= 0)
        //    {
        //        result = accountHeadService.SaveAccountHead(0, vm.AccountHead);
        //    }
        //    else
        //    {
        //        result = accountHeadService.SaveAccountHead(vm.AccountHead.AccountHeadId, vm.AccountHead);
        //    }
        //    if (result)
        //    {
        //        TempData["successMessage"] = "Operation Successful !";
        //    }
        //    return RedirectToAction("Index", new { companyId = vm.AccountHead.CompanyId });
        //}

        // GET: AccountHeads/Delete/5
        //public ActionResult Delete(long id)
        //{
        //    AccountHeadModel accountHead = accountHeadService.GetAccountHead(id);
        //    if (accountHead == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(accountHead);
        //}

        // POST: AccountHeads/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(long id)
        //{
        //    bool result = accountHeadService.DeleteAccountHead(id);
        //    if (result)
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}



        //[HttpPost]
        //public JsonResult AutoComplete(string prefix)
        //{
        //    int companyId = Convert.ToInt32(Session["CompanyId"]);
        //    //int companyId = Convert.ToInt32(Request.QueryString["companyId"]);
        //    var accountHeads = accountHeadService.GetAccountHeadAutoComplete(prefix, companyId);
        //    return Json(accountHeads);
        //}




        //[SessionExpire]
        //[HttpGet]
        //public JsonResult GetNextAccountHead(int parentId)
        //{
        //    string newAccountHead = accountHeadService.GenerateNewAccountHead(parentId);

        //    return Json(newAccountHead, JsonRequestBehavior.AllowGet);
        //}


        ////[SessionExpire]
        ////[HttpGet]
        ////public ActionResult TreeView()
        ////{
        ////    return View();
        ////}

        //[SessionExpire]
        //[HttpGet]
        //public JsonResult TreeViewItems()
        //{
        //    var accountHeadTreeViews = accountHeadService.GetAccountHeadTreeView();

        //    return Json(accountHeadTreeViews, JsonRequestBehavior.AllowGet);
        //}

        ////-----------------------------Tree view Menu-----------------------
        //public ActionResult OnDemand()
        //{
        //    List<AccountHead> all = new List<AccountHead>();
        //    using (ERPEntities dc = new ERPEntities())
        //    {
        //        all = dc.AccountHeads.Where(a => a.ParentId == null && a.CompanyId == 28).ToList();
        //    }
        //    return View(all);
        //}

        //public JsonResult GetSubMenu(string pid)
        //{
        //    // this action for Get Sub Menus from database and return as json data
        //    //System.Threading.Thread.Sleep(5000);
        //    List<AccountHead> subMenus = new List<AccountHead>();
        //    int pID = 0;
        //    int.TryParse(pid, out pID);
        //    using (ERPEntities dc = new ERPEntities())
        //    {
        //        subMenus = dc.AccountHeads.Where(a => a.ParentId == pID && a.CompanyId == 28).ToList();
        //    }

        //    return new JsonResult { Data = subMenus, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        //}


        ////--------------------------------Final----------------------------------------
        ////public ActionResult TreeView(int companyId)
        ////{
        ////    //int companyId = Convert.ToInt32(Session["CompanyId"]);
        ////    List<AccountHeadModel> accountHeads = accountHeadService.GetAccountHeadsByCompany(companyId);
        ////    return View(accountHeads);
        ////}

        //[HttpGet]
        //[SessionExpire]
        //public ActionResult TestTreeView(int companyId)
        //{


        //    companyId = 28;
        //    List<AccountHeadProcessModel> accountHeads = accountHeadService.GetAccountHeadsTreeViewByCompany(companyId);
        //    return View(accountHeads);
        //}







    }
}

KGERP/Views/AccountHeads/CreateOrEdit.cshtml
@model KGERP.ViewModel.AccountHeadViewModel

@{
    ViewBag.Title = "CreateOrEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.AccountHead.AccountHeadId)
    @Html.HiddenFor(model => model.AccountHead.CompanyId)

<div class="form-horizontal">
    <h4>Account Head </h4>
    <hr style="border-color:#006747; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.AccountHead.ParentId, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.AccountHead.ParentHead.AccName, new { htmlAttributes = new { @class = "form-control", @name = "accountName", @id = "accountName" } })
                @Html.HiddenFor(x => x.AccountHead.ParentId, new { @id = "parentId", @name = "parentId" })
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.AccountHead.AccCode, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.AccountHead.AccCode, new { htmlAttributes = new { @class = "form-control", @id = "txtAccountCode" } })
                @Html.ValidationMessageFor(model => model.AccountHead.AccCode, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.AccountHead.AccName, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.AccountHead.AccName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountHead.AccName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>



    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.AccountHead.Remarks, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.AccountHead.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountHead.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    

    <div class="col-md-12">
        <div class="col-md-3">
            <a href="@Url.Action("Index")" class="btn btn-danger">
                <span class="glyphicon glyphicon-arrow-left"></span> Back
            </a>
        </div>
        <div class="col-md-6">
            @if (TempData["message"] != null)
            {
                <b class="text-danger">@TempData["message"]</b>
            }
        </div>
        <div class="col-md-3">
            <input type="submit"  value="Save"  class="btn btn-primary pull-right" />
        </div>
    </div>
</div>
}



@if (TempData["errMessage"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("This Account Head Already Exists");
        };
    </script>
}


@if (TempData["DataSave"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("Data Save Successfully!");
        };
    </script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")


    <style type="text/css">
        .image {
            float: left;
            max-height: 50px;
            max-width: 50px;
            margin-right: 10px;
        }

        .name {
            margin: 0;
            padding: 0;
        }

        .username {
            display: block;
            font-weight: bold;
            margin-bottom: 1em;
        }

        .ui-autocomplete {
            max-height: 320px;
            overflow: auto;
        }
    </style>
    <script type="text/javascript">
        $(function () {
            $("#accountName").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/AccountHeads/AutoComplete/',
                        //data: "{ 'prefix': '" + request.term + "'}",
                        data: '{"prefix":"' + request.term + '"}',
                        dataType: "json",
                        type: "POST",
                        cache: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            //alert(response.responseText);
                        },
                        failure: function (response) {
                            //alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#parentId").val(i.item.val);
                },
                minLength: 1,
                change: function (event, ui) {
                    loadNextAccountHead(ui.item.val);
                },
                cache: true

            }).focus(function () {
                $(this).autocomplete("search");
            });
        });



        function loadNextAccountHead(parentId) {
            $.ajax({
                url: '/AccountHeads/GetNextAccountHead?parentId=' + parentId,
                type: "GET",
                async: true,
                processData: false,
                cache: false,
                success: function (data) {

                    var result = JSON.parse(data);
                    console.log(result);
                    $('#txtAccountCode').val(result);
                    $('#txtAccountCode').prop("readonly", true);

                },
                error: function (xhr) {
                    alert('error');
                }
            });

        }
    </script>
}

KGERP/Views/AccountHeads/Delete.cshtml
@model KGERP.Service.ServiceModel.AccountHeadModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Are you sure you want to delete AccountHead?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KGERP/Views/AccountHeads/Details.cshtml
@model KGERP.Data.Models.AccountHead

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
<div>
    <h4>Account Head</h4>
    <hr style="border-color:red; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Actcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Actname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actname)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Create", new { id = Model.OID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KGERP/Views/AccountHeads/Edit.cshtml
@model KGERP.Data.Models.AccountHead

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccountHead</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OID)

        <div class="form-group">
            @Html.LabelFor(model => model.Actcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Actcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Actname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KGERP/Views/AccountHeads/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<KGERP.Service.ServiceModel.AccountHeadModel>
@using PagedList;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var message = TempData["successMessage"];
}
@using (Html.BeginForm("Index", "AccountHeads", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-6">
            <h4><b>Account Head List</b></h4>

        </div>
        <div class="col-md-4">
            <div class="col-md-10">@Html.TextBox("searchText", null, new { @autocomplete = "off", @class = "form-control pull-right", @placeholder = "Search..." })</div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-success">Search&nbsp;<i class="fa fa-search"></i></button>
            </div>
        </div>

        <div class="col-md-2">
            <a href="@Url.Action("CreateOrEdit", new { id = 0 })" title="New Head" class="btn btn-primary pull-right">
                <span class="glyphicon glyphicon-user"></span> Add
            </a>
        </div>
    </div>
}
<hr style="border-color:#006747; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />
<table class="table">
    <tr style="background-color:#009270;color:#FFFFFF">
        <th>
            @Html.DisplayNameFor(model => model.First().AccCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AccName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().ParentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TierNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Remarks)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentHead.AccName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TierNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remarks)
            </td>
            <td>
                <a href="@Url.Action("CreateOrEdit", new { id = item.AccountHeadId })" title="Edit" class="btn btn-info btn-xs">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
                <a href="@Url.Action("Delete", new { id = item.AccountHeadId })" title="Delete" class="btn btn-danger btn-xs">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
    }
</table>
@if (Model.PageCount > 1)
{
    <span class="btn btn-success">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    </span>
    <span class="checkbox">
        @Html.PagedListPager(Model, Page_No => Url.Action("Index", "AccountHeads",
                      new { Page_No, Sorting_Order = Request.QueryString["Search"],SearchText= Request.QueryString["searchText"] }))
    </span>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

    var message = '@message';
    if(message){
        alert(message);
    }

    </script>

}

KGERP/Views/AccountHeads/OnDemand.cshtml
@model List<KGERP.Data.Models.AccountHead>
@{
    ViewBag.Title = "OnDemand";
}


<style>
    .loadingP {
        background-image: url('../Images/generated-image.gif');
        width: 15px;
        display: inline-block;
    }

    .collapse {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -36px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .expand {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -50px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .treeview ul {
        font: 14px Arial, Sans-Serif;
        margin: 0px;
        padding-left: 20px;
        list-style: none;
    }

    .treeview > li > a {
        font-weight: bold;
    }

    .treeview li a {
        padding: 4px;
        font-size: 12px;
        display: inline-block;
        text-decoration: none;
        width: auto;
    }
</style>
@* Here We will add some css for looks treeview good *@

<h2 class="text-center" style="border:1px solid #32527B; padding:0px; color:white; background-color:#32527B">Chart of Accounts - Treeview</h2>
<div style="border:1px solid black; padding:0px;  background-color:#FAFAFA;font:bold">
    @{
        <div class="treeview">
            @{
                if (Model != null && Model.Count() > 0)
                {
                    @*Here I will going to load Treeview menus*@
                    <ul>
                        @foreach (var i in Model)
                        {
                            <li>
                                <span class="collapse collapsible" data-loaded="false" pid="@i.AccountHeadId">&nbsp;</span>
                                @* Here I have added the above span for collapsible button for treeview *@
                                @* and data-loaded="false" means its sub menu not loaded yet from database *@
                                <span>
                                    <a href="@Url.Action("Index","Home")">@i.AccName</a>
                                </span>
                            </li>
                        }
                    </ul>
                }
            }
        </div>
    }
</div>

@section Scripts {
    <script src="~/Scripts/ActiveTreeView/treeView.js"></script>
    <script type="text/javascript">

    </script>

}

KGERP/Views/AccountHeads/TestTreeView.cshtml
@model KGERP.Service.ServiceModel.AccountHeadModel>
@using System.Web.UI.WebControls
@using KGERP.TreeViewModel


<h2 class="text-center" style="border:1px solid #32527B; padding:0px; color:white; background-color:#32527B">Chart of Accounts - Treeview</h2>
@*<link href="~/Content/jsTree/themes/default/style.min.css" rel="stylesheet" />*@


<link href="~/Scripts/TreeView/dist/themes/default/style.min.css" rel="stylesheet" />
<div class="form-body">
    <div id="jstree">
        @(Html.TreeView(Model).EmptyContent("<span style='font-size:15px;'>General Ledger</span>")
                                                                  .Children(m => m.AccountHead1)
                                                                  .HtmlAttributes(new { id = "tree" })
                                                              .ChildrenHtmlAttributes(new { @class = "subItem" })
                                                                  .ItemText(m => m.AccName)
                                                                  .ItemTemplate(
                                                @<text>
                                                    <a href="#"  onclick="getChartOfAccount('@item.AccountHeadId')" title="@item.AccountHeadId" desc="@item.AccName"><span style="font-size:15px;">@(item.AccCode + "-" + item.AccName)</span></a>
                                                </text>)
        )
    </div>
</div>
@section scripts
{
    @*<script src="~/Scripts/jsTree3/jstree.min.js"></script>*@
    <script src="~/Scripts/TreeView/dist/jstree.js"></script>
    <script>
        $(function () {
            var selectedData;
            $('#jstree').jstree({
                "core": {
                    "multiple": true,
                    "check_callback": false,
                    'themes': {
                        "responsive": true,
                        'variant': 'larg',
                        'stripes': true,
                        'dots': true
                    }
                },
                "types": {
                    "default": {
                        "icon": "glyphicon glyphicon-plus-sign"
                    }
                },
                "plugins": ["conditionalselect"]
            });
        });


        function getChartOfAccount(accountHeadId) {
           // alert(accountHeadId);
        }
    </script>
}




































@*<h2>Chart of Accounting TreeView</h2>
    <div id="container">

    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")

        <script type="text/javascript">
            $(function () {
                $('#container').jstree({
                    'core': {
                        'data': {
                            "url": "/AccountHeads/TreeViewItems",
                            "dataType": "json" // needed only if you do not supply JSON headers
                        }
                    }
                });
            });
        </script>

    }*@

KGERP/Views/AccountHeads/TreeView.cshtml
@model KGERP.ViewModel.AccountHeadViewModel
@using System.Web.UI.WebControls
@using KGERP.TreeViewModel


<h2 class="text-center" style="border:1px solid #32527B; padding:0px; color:white; background-color:#32527B">Chart of Accounts - Treeview</h2>
@*<link href="~/Content/jsTree/themes/default/style.min.css" rel="stylesheet" />*@


<link href="~/Scripts/TreeView/dist/themes/default/style.min.css" rel="stylesheet" />
<div class="form-body">
    <div id="jstree">
        @(Html.TreeView(Model.AccountHeads).EmptyContent("<span style='font-size:15px;'>General Ledger</span>")
                                                                                          .Children(m => m.AccountHeadProcess1)
                                                                                          .HtmlAttributes(new { id = "tree" })
                                                                                      .ChildrenHtmlAttributes(new { @class = "subItem" })
                                                                                          .ItemText(m => m.AccName)
                                                                                          .ItemTemplate(
                                                                        @<text>
                                                                            <a href="#" onclick="getChartOfAccount('@item.Id','@item.LayerNo')" title="@item.Id" desc="@item.AccName"><span style="font-size:15px;">@(item.AccCode + "-" + item.AccName)</span></a>
                                                                        </text>)
        )
    </div>
</div>

<div id="divChildAccountHead">
</div>




@section scripts
{
    @*<script src="~/Scripts/jsTree3/jstree.min.js"></script>*@
    @*<script src="~/Scripts/TreeView/dist/jstree.js"></script>*@
    <script>
        //$(function () {
        //    var selectedData;
        //    $('#jstree').jstree({
        //        "core": {
        //            "multiple": true,
        //            "check_callback": false,
        //            'themes': {
        //                "responsive": true,
        //                'variant': 'larg',
        //                'stripes': true,
        //                'dots': true
        //            }
        //        },
        //        "types": {
        //            "default": {
        //                "icon": "glyphicon glyphicon-plus-sign"
        //            }
        //        },
        //        "plugins": ["conditionalselect"]
        //    });
        //});


        function getChartOfAccount(accountHeadId, layerNo) {
            alert();
            //$.ajax({
            //    url: '/HeadGLs/GetChildHead?accountHeadId=' + accountHeadId + '&layerNo=' + layerNo + "",
            //    type: "GET",
            //    async: true,
            //    processData: false,
            //    cache: false,
            //    success: function (data) {
            //        $('#divChildAccountHead').html(data);
            //    },
            //    error: function (xhr) {
            //        alert('error');
            //    }
            //});
        }
    </script>
}




































@*<h2>Chart of Accounting TreeView</h2>
    <div id="container">

    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")

        <script type="text/javascript">
            $(function () {
                $('#container').jstree({
                    'core': {
                        'data': {
                            "url": "/AccountHeads/TreeViewItems",
                            "dataType": "json" // needed only if you do not supply JSON headers
                        }
                    }
                });
            });
        </script>

    }*@