KGERP/Controllers/CompanyController.cs
using KGERP.Data.Models;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class CompanyController : Controller
    {
        private readonly ICompanyService companyService;
        public CompanyController(ICompanyService companyService)
        {
            this.companyService = companyService;
        }

        [SessionExpire]
        [HttpGet]
        public ActionResult Index(string searchText)
        {
            List<CompanyModel> companies = companyService.GetCompanies(searchText);
            List<CompanyModel> companiesWithImage = companies.Select(x => new CompanyModel
            {
                CompanyId = x.CompanyId,
                Name = x.Name,
                ShortName = x.ShortName,
                OrderNo = x.OrderNo,
                MushokNo = x.MushokNo,
                IsCompany = x.IsCompany,
                CompanyLogo = string.Format("{0}://{1}", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority) + "/Images/Logo/" + (string.IsNullOrEmpty(x.CompanyLogo) ? "logo.png" : x.CompanyLogo),
            }).ToList();
            return View(companiesWithImage);
        }

        [HttpGet]
        [SessionExpire]
        public ActionResult CreateOrEdit(int id)
        {
            CompanyModel company = companyService.GetCompany(id);
            company.CompanyLogo = string.Format("{0}://{1}", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority) + "/Images/Logo/" + (string.IsNullOrEmpty(company.CompanyLogo) ? "logo.png" : company.CompanyLogo);
            return View(company);
        }

        [HttpPost]
        [SessionExpire]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(CompanyModel model)
        {
            ModelState.Clear();
            string message = string.Empty;
            bool result = false;

            if (model.CompanyLogoUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(model.CompanyLogoUpload.FileName);
                string extension = Path.GetExtension(model.CompanyLogoUpload.FileName);
                fileName = fileName + "_" + DateTime.Now.ToString("yymmssfff") + extension;
                model.CompanyLogo = fileName;
                model.CompanyLogoUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Logo/"), fileName));
            }

            if (model.CompanyId <= 0)
            {
                result = companyService.SaveCompany(0, model);
            }
            else
            {
                result = companyService.SaveCompany(model.CompanyId, model);
            }
            if (result)
            {
                TempData["message"] = "Company Saved Successfully !";
            }
            else
            {
                TempData["message"] = "Company not Saved !";
            }
            return RedirectToAction("Index");
        }


    }

}

KGERP/Views/Company/BusinessHead.cshtml
@model KGERP.Service.ServiceModel.BusinessHeadModel
@using KGERP.Utility;
@{
    ViewData["Title"] = "Company Head";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>

<section class="content-header">
    <h1>Company Head</h1>
</section>
@using (Html.BeginForm("BusinessHead", "Company", FormMethod.Post, new { id = "entryForm", @class = "formValidator" }))
{
    <section class="content">
        <div class="box">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.ActionType)
            <div class="box">
                <div class="box-body">
                    @*<div class="row">
                            <div style="display:flex;">
                                @Html.RadioButtonFor(x => x.BusinessType, BusinessTypeEnum.Company, new { @class = "form-check-inline", @id = "radioC", style = "margin-left:48%;" })
                                <label class="form-check-label" for="radioC">
                                    Company
                                </label>
                                @Html.RadioButtonFor(x => x.BusinessType, BusinessTypeEnum.Division, new { @class = "form-check-inline", @id = "radioD" })
                                <label class="form-check-label" for="radioD">
                                    Division
                                </label>
                            </div>
                        </div>*@
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="BusinessType" class="control-label">Business Type</label>
                                @Html.EnumDropDownListFor(x => x.BusinessType, "--Select--", new { @class = "form-control", @data_val = "true", @onchange = "loadarFunction()" })
                                @Html.ValidationMessageFor(x => x.BusinessType, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="BusineesId_Fk" class="control-label">Company/Division</label>
                                @Html.DropDownListFor(x => x.BusineesId_Fk, new SelectList(String.Empty, "value", "text"), new { @class = "form-control", @data_val = "true" })
                                @Html.ValidationMessageFor(x => x.BusineesId_Fk, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="CompanyId" class="control-label">Employee</label>
                                @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @autocomplete = "on", @class = "form-control", required = "required" } })
                                @Html.HiddenFor(model => model.EmployeeId)
                                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @autocomplete = "off", @class = "datepicker form-control", @data_val = "false" } })
                                    @Html.ValidationMessageFor(x => x.FromDate, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" id="btnSave" class="btn btn-primary pull-right" style="margin-left:3px;">
                                <i class='fa fa-plus'></i>
                                <span>Add</span>
                            </button>
                            <label onclick="resetForm()" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>&nbsp;Reset</label>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    @*<div class="row">
                        <div class="col-md-12 pull-right">
                            <button type="submit" id="btnSave" class="btn btn-primary pull-right">
                                <i class='fa fa-plus'></i>
                                <span>Add</span>
                            </button>
                            <label onclick="resetForm()" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>&nbsp;Reset</label>
                        </div>
                    </div>*@
                </div>
                <div class="box-body">
                    @if (Model.DataList != null && Model.DataList.Count() > 0)
                    {
                        <div class="table-responsive col-md-12  text-nowrap">
                            <table id="KgErpDataTable" class="table table-responsive-md table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>SL</th>
                                        <th>Business</th>
                                        <th>Name</th>
                                        <th>Employee</th>
                                        <th>From Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.DataList)
                                    {

                                        <tr>
                                            <td>@(i++)</td>
                                            <td>@item.BusinessType</td>
                                            <td>@item.BusinessName</td>
                                            <td>@item.EmployeeName</td>
                                            <td>@item.FromDateString</td>
                                            <td>
                                                <a id="@item.Id" onclick="makeEditble(@item.Id)" class="linkPointer" title="Edit"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                                @*<a id="@item.Id" onclick="makeDeletale(@item.Id)" class="linkPointer" data-toggle="modal" data-target="#deleteProcurementPurchaseOrderSlaveModal" title="Delete" data-placement="top"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></a>*@
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    }
                </div>
            </div>
        </div>
    </section>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
<script type="text/javascript">
        $(document).ready(function () {
            $(function () {
                $("#EmployeeName").autocomplete({
                    source: function (request, response) {
                        $.ajax({
                            type: "GET",
                            url: "/AutoComplete/GetAllEmployeeAutoComplete",
                            dataType: "json",
                            data: { prefix: request.term },
                            success: function (data) {
                                response($.map(data, function (item) {
                                    return { label: item.Name, value: item.Name, id: item.Id };
                                }));
                            },
                            error: function (e) {
                                // Handle error, if needed
                            }
                        });
                    },
                    minLength: 1,
                    delay: 500,
                    autoFocus: true,
                    select: function (event, ui) {
                        $("#EmployeeId").val(ui.item.id);
                    }
                });
            });
        });

        function makeEditble(id) {
            $("#btnSave").text("Update");
              $("#ActionType").val('@(ActionEnum.Edit)');
             bindProperty(id);
        };
        function loadarFunction() {

            var businessTypeId = $("#BusinessType").val();
            if (businessTypeId == 0) {
                return;
            }
            if (businessTypeId == @((int)BusinessTypeEnum.Company)) {
                LoadCompany();
            }
            if (businessTypeId == @((int)BusinessTypeEnum.Division))
            {
                LoadDepartment();
            }
        }

        function bindProperty(id) {
                $.ajax({
                    type: "GET",
                    url: "/Company/GetBusinessHeadById",
                    data: { id: id },
                    success: function (data) {
                        console.log(data);
                        const fieldsToDisplay = ['Id', 'EmployeeId', 'EmployeeName', 'FromDateString', 'ToDateString', 'BusinessTypeInt', 'BusineesId_Fk'];
                        fieldsToDisplay.forEach((item) => {
                            if (item == "BusinessTypeInt") {
                                if (data['BusinessType'] == @((int)BusinessTypeEnum.Company)) {
                                    $("#BusinessType").val(data[item]);
                                    LoadCompany(data['BusineesId_Fk']);
                                }
                                if (data['BusinessType'] == @((int)BusinessTypeEnum.Division)) {
                                    $("#BusinessType").val(data[item]);
                                    LoadDepartment(data['BusineesId_Fk']);
                                }
                            }
                            if (item == "FromDateString") {
                                var f = $("#FromDate");
                                if (f != null) {
                                    f.val(data[item]);
                                }
                            }
                            var formField = $("#" + item);
                            if (formField != null) {
                                formField.val(data[item]);
                            }

                        });
                    }
                })

        }
    function LoadCompany(id) {
            $.ajax({
                type: "GET",
                url: "/AutoComplete/GetAllCompanyAutoComplete",
                success: function (res) {
                    $("#BusineesId_Fk").html("");
                    var content = '<option>Select Company</option>';
                    $.each(res,
                        function (index, itemData) {
                            content += '<option value=' + itemData.Id + '>' + itemData.Name + '</option>'
                        })
                    $("#BusineesId_Fk").append(content)
                    if (id != null) {
                        $("#BusineesId_Fk").val(id);
                    }
                }
            })
        }
        function LoadDepartment(id) {
            $.ajax({
                type: "GET",
                url: "/AutoComplete/GetAllDepartmentAutoComplete",
               // data: { CompanyId: CompanyId },
                success: function (res) {
                    $("#BusineesId_Fk").html("");
                    var content = '<option>Select Division</option>';
                    $.each(res,
                        function (index, itemData) {
                            content += '<option value=' + itemData.Id + '>' + itemData.Name + '</option>'
                        })
                    $("#BusineesId_Fk").append(content);
                    if (id != null) {
                        $("#BusineesId_Fk").val(id);
                    }
                }
            })
    }
    $('.datepicker').datepicker({
        dateFormat: "yy/mm/dd",
        showOn: 'both',
        buttonText: "<i class='fa fa-calendar'></i>",
        changeMonth: true,
        changeYear: true,
        yearRange: "2001:+50"
    });
    function resetForm() {
        $("#FromDate").val("@(DateTime.Today.ToString("yyyy/MM/dd"))");
        $("#btnSave").text("Add");
        $("#ActionType").val('@(ActionEnum.Add)');
        const fieldsToDisplay = ['Id', 'EmployeeId', 'EmployeeName', 'FromDate', 'ToDate', 'BusinessType', 'BusineesId_Fk'];
        fieldsToDisplay.forEach((item) => {
            var f = $("#" + item);
            if (f != null) {
                if (item == "Id") {
                    f.val(0);
                } else {

                    f.val('');
                }
            }
           
        });
    }

</script>
    }

KGERP/Views/Company/CreateOrEdit.cshtml
@model KGERP.Service.ServiceModel.CompanyModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CreateOrEdit", "Company", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return jQueryAjaxPost(this);" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CompanyId)

<div class="form-horizontal">
    <h4>Company @Model.ButtonName</h4>
    <hr style="border-color:#ff0000; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompanyType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CompanyType, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MushokNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MushokNo, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IsCompany, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsCompany)
                @Html.ValidationMessageFor(model => model.IsCompany, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CompanyLogo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-8">
            <img src="@Url.Content(Model.CompanyLogo)" style="margin:5px;" height="150" width="150" id="imagePreview" />
            <input type="file" name="CompanyLogoUpload" accept="image/jpg, image/jpeg, image/png" onchange="showImagePreview(this, document.getElementById('imagePreview'))" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-3 col-md-10">
            <a href="@Url.Action("Index",new {companyId=Model.CompanyId, productType=Request.QueryString["productType"]})" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove-circle"></span>   Close
            </a>
            <button type="submit" class="btn btn-primary" onclick="javascript: return SubmitForm();" style="margin-left: 20px;"><span class="glyphicon glyphicon-floppy-disk"></span>@Model.ButtonName</button>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

        //JQuery Ajax Form Submit Begin
        function jQueryAjaxPost(form) {
            $validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                var ajaxConfig = {
                    type: "POST",
                    url: from.action,
                    data: new FormData(form),
                    success: function (response) {
                        var url = '@Url.Action("Index", "Company")';
                        window.location.href = url;
                    }
                };

                if ($(form).attr('enctype') == "multipart/form-data") {
                    ajaxConfig["contentType"] = false;
                    ajaxConfig["processData"] = false;
                }
                $ajax(ajaxConfig);
            }
            return false;
        }

        //JQuery Ajax Form Submit End

        //Image Preview Begin
        function showImagePreview(imageUploader, previewImage) {
            if (imageUploader.files && imageUploader.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(previewImage).attr('src', e.target.result);
                }
                reader.readAsDataURL(imageUploader.files[0]);
            }
        }

        //Image Preview End

  

    </script>

}

KGERP/Views/Company/Index.cshtml
@model IList<KGERP.Service.ServiceModel.CompanyModel>
@{
    ViewData["Title"] = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/CustomCss/search-form.css" rel="stylesheet" />

@using (Html.BeginForm("Index", "Company", FormMethod.Get, new { @class = "example" }))
{
    <div class="row">
        <div class="col-md-6">
            <span style="font-size:20px;font-weight:bold">
                Companies
            </span>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.Editor("searchText", new { htmlAttributes = new { @autocomplete = "off", value = "", @placeholder = "Search..." } })
                <button type="submit"><i class="fa fa-search "></i></button>
            </div>
        </div>
        <div class="col-md-2 pull-right">
            <div class="form-group">
                <a href="@Url.Action("CreateOrEdit", new { id = 0})" class="btn btn-primary pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span> Add Company
                </a>
            </div>
        </div>
    </div>
}

<div class="row">
    <hr style="border-color:#32527B; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    <table id="KgErpDataTable" class="table table-striped table-condensed">
        <tr style="background-color:#3c8dbc;color:#ffffff">
            <th>
                SL
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().CompanyLogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().CompanyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().ShortName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().OrderNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().IsCompany)
            </th>

            <th class="text-center">Action</th>
        </tr>

        @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td>
                    @(item.Index + 1)
                </td>
                <td>
                    <img src="@Url.Content(item.Data.CompanyLogo)" height="25" width="25" alt="CompanyLogo">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.CompanyId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Data.ShortName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.OrderNo)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Data.IsCompany)
                </td>

                <td class="text-center">
                    <a href="@Url.Action("CreateOrEdit", new { id = item.Data.CompanyId})" title="Edit" class="btn btn-info btn-xs">
                        <i class="fa fa-edit" style="font-size:15px;" aria-hidden="true"></i>
                    </a>

                    @*<a href="@Url.Action("Delete", new { id = item.Data.ProductId,companyId=Request.QueryString["companyId"],type=Request.QueryString["type"] })" title="Delete" class="btn btn-danger btn-xs">
                            <i class="fa fa-trash" style="font-size:15px;" aria-hidden="true"></i>
                        </a>*@
                </td>
            </tr>
        }

    </table>


</div>


@section Scripts{
    <script type="text/javascript">


    </script>
}