KGERP/Controllers/HeadGLsController.cs
using KGERP.Data.Models;
using KGERP.Service.Implementation;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using KGERP.ViewModel;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class HeadGLsController : BaseController
    {
        private readonly IHeadGLService accountHeadService;
       
        private readonly AccountingService _accountingService;
        public HeadGLsController(IHeadGLService accountHeadService,ERPEntities db)
        {
            this.accountHeadService = accountHeadService;
           
            _accountingService = new AccountingService(db);
        }
        [HttpPost]
        public JsonResult AutoComplete(string prefix)
        {
            int companyId = Convert.ToInt32(Session["CompanyId"]);
            var accountHeads = accountHeadService.GetAccountHeadAutoComplete(prefix, companyId);
            return Json(accountHeads);
        }
        [HttpPost]
        public JsonResult MemberHeadAutoComplete(string prefix)
        {
            int companyId = Convert.ToInt32(Session["CompanyId"]);
            var accountHeads = accountHeadService.GetMemberHeadAutoComplete(prefix, companyId);
            return Json(accountHeads);
        }

        [HttpPost]
        public JsonResult AutoCompleteHeadGLGet(string prefix, int companyId)
        {

            var accountHeads = accountHeadService.GetAccountHeadAutoComplete(prefix, companyId);
            return Json(accountHeads);
        }

        [HttpPost]
        public JsonResult AutoCompleteAllAccountsHead(string prefix)
        {
            int companyId = Convert.ToInt32(Session["CompanyId"]);
            var accountHeads = accountHeadService.AllAccountsHead(prefix, companyId);
            return Json(accountHeads);
        }
        public ActionResult TreeView(int companyId)
        {
            HeadGLViewModel vm = new HeadGLViewModel();
            var company = _accountingService.GetCompanyById(companyId);
            vm.CompanyName = company.Name + " (" + company.ShortName + ")";
            vm.Head1s = accountHeadService.GetAccountHeadsTreeViewByCompany(companyId);
            return View(vm);
        }
        [HttpGet]
        [SessionExpire]
        public PartialViewResult GetSelectionWindow(int accountHeadId, int layerNo, string accCode, string accName)
        {
            AccountHeadProcessModel accountHeadProcessModel = accountHeadService.GetSelectedItem(accountHeadId, layerNo, accCode, accName);
            return PartialView("~/Views/HeadGLs/_selectionWindow.cshtml", accountHeadProcessModel);
        }

        [HttpGet]
        [SessionExpire]
        public PartialViewResult GetChildHead(int accountHeadId, int layerNo, string accCode, string accName, string status)
        {
            AccountHeadProcessModel accountHeadProcessModel = new AccountHeadProcessModel();
            if (status.Equals("create"))
            {
                accountHeadProcessModel = accountHeadService.GetAccountHeadProcessCreate(accountHeadId, layerNo, status);
            }

            if (status.Equals("update"))
            {
                accountHeadProcessModel = accountHeadService.GetAccountHeadProcessUpdate(accountHeadId, layerNo, status);
            }
            if (status.Equals("delete"))
            {
                accountHeadProcessModel = accountHeadService.GetAccountHeadProcessDelete(accountHeadId, layerNo, status);
            }
            ModelState.Clear();
            return PartialView("~/Views/HeadGLs/_childHeadCreateOrEdit.cshtml", accountHeadProcessModel);

        }

        [HttpPost]
        [SessionExpire]
        public ActionResult Create(AccountHeadProcessModel model)
        {
            bool result = accountHeadService.SaveAccountHead(model);
            if (result)
            {
                TempData["successMessage"] = "Operation Successful!";
            }
            return RedirectToAction("TreeView", new { model.CompanyId });
        }


        [HttpPost]
        public ActionResult GetTeritorySelectModelsByZone(int zoneId)
        {
            int companyId = Convert.ToInt32(Session["CompanyId"]);
            List<SelectModel> teritories = accountHeadService.GetTeritorySelectModelsByZone(companyId, zoneId);
            return Json(teritories, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [SessionExpire]
        public async Task<ActionResult> AccountingHeadList(int companyId)
        {
            if (companyId > 0)
            {
                Session["CompanyId"] = companyId;
            }
            VMAccountHead vmAccountHead = new VMAccountHead();
            vmAccountHead = await accountHeadService.GetAccountingHeadList(companyId);
            return View(vmAccountHead);
        }

    }
}

KGERP/Controllers/ReportController.cs
using AutoMapper.Mappers;
using DocumentFormat.OpenXml.Drawing.Charts;
using DocumentFormat.OpenXml.EMMA;
using KGERP.Controllers.Custom_Authorization;

using KGERP.Data.CustomModel;
using KGERP.Data.Models;
using KGERP.Service.Implementation;
using KGERP.Service.Implementation.ApprovalSystemService;

using KGERP.Service.Interface;

using KGERP.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security;
using System.Threading.Tasks;
using System.Web.Mvc;
using static KGERP.Utility.Util.PermissionCollection.Crms;

namespace KGERP.Controllers
{
    //[SessionExpire]
    //test azim
    public class ReportController : Controller
    {


        private readonly ICompanyService companyService;
        private readonly IVoucherTypeService voucherTypeService;

        private readonly AccountingService _accountingService;
        private readonly ConfigurationService _configrationService;
        private readonly IApproval_Service _appService;



        string password = "KGerp@321";
        string admin = "Administrator";
        string url = "http://192.168.2.2/ReportServer/?%2fErpReport/";
        public ReportController(ERPEntities db,
              ICompanyService companyService, IVoucherTypeService voucherTypeService,
               ConfigurationService configurationService,
              IApproval_Service _appService)
        {

            this.companyService = companyService;
            this.voucherTypeService = voucherTypeService;

            this._appService = _appService;

            _accountingService = new AccountingService(db);
            _configrationService = configurationService;

        }

        [HttpGet]
        [SessionExpire]
        public ActionResult Index()
        {
            return View();
        }


        // GET: Report
        [HttpGet]

        public ActionResult GetEmployeeReport(string employeeId)
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "Employee&rs:Command=Render&rs:Format=PDF&EmployeeId=" + employeeId;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        [HttpGet]

        public ActionResult ReportTemplate(int companyId, string reportName, string reportDescription)
        {
            var rptInfo = new ReportInfo
            {
                ReportName = reportName,
                ReportDescription = reportDescription,
                ReportURL = String.Format("../../Reports/ReportTemplate.aspx?ReportName={0}&ReportDescription={1}&Height={2}", reportName, reportDescription, 650),
                Width = 100,
                Height = 650
            };
            return View(rptInfo);
        }


        [HttpGet]

        public ActionResult CRReportTemplate(int companyId, string reportName, string reportDescription)
        {
            var rptInfo = new ReportInfo
            {
                ReportName = reportName,
                ReportDescription = reportDescription,
                ReportURL = String.Format("../../Reports/ReportTemplate.aspx?ReportName={0}&ReportDescription={1}&Height={2}&companyId={3}", reportName, reportDescription, 650, companyId),
                Width = 100,
                Height = 650
            };
            return View(rptInfo);
        }
        // GET: Report
        [HttpGet]

        public ActionResult GetOrderInvoiceReport(string orderMasterId)
        {
            var companyId = Convert.ToInt32(Request.QueryString["companyId"]);
            string reportURL;
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            if (companyId == (int)CompanyName.KrishibidFarmMachineryAndAutomobilesLimited)
            {
                reportURL = url + "KFMALOrderInvoice&rs:Command=Render&rs:Format=PDF&OrderMasterId=" + orderMasterId;
            }

            else
            {
                reportURL = url + "OrderInvoice&rs:Command=Render&rs:Format=PDF&OrderMasterId=" + orderMasterId;
            }


            return File(client.DownloadData(reportURL), "application/pdf");
        }

        [HttpGet]

        public ActionResult GetEmiReport(int emiId)
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "EmiReportForKFMAL&rs:Command=Render&rs:Format=PDF&EmiId=" + emiId;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        [HttpGet]

        public ActionResult GetKgeComOrderInvoiceReport(string orderMasterId)
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "KGeComInvoiceReport&rs:Command=Render&rs:Format=PDF&OrderMasterId=" + orderMasterId;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        [HttpGet]

        public ActionResult GetKFMALCOstingReport(int storeId)
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "CogsCostingReport&rs:Command=Render&rs:Format=PDF&StoreId=" + storeId;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        //[HttpGet]
        // 
        //public ActionResult GetStockReport()
        //{
        //    NetworkCredential nwc = new NetworkCredential(admin, AdminPassword);
        //    WebClient client = new WebClient();
        //    client.Credentials = nwc;
        //    string reportURL =url + "StockReport&rs:Command=Render&rs:Format=PDF";
        //    //string reportURL = url + "StockReport" ;
        //    return File(client.DownloadData(reportURL), "application/pdf");
        //}

        [HttpGet]

        public ActionResult GetStockReport(int companyId, string reportName)
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);



            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = string.Format(url + "{0}&rs:Command=Render&rs:Format=PDF&CompanyId={1}", reportName, companyId);
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        [HttpGet]

        public ActionResult GetEcomStockReport()
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "KGeComCurrentStock&rs:Command=Render&rs:Format=PDF";
            //string reportURL = url + "StockReport" ;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        public ActionResult GetRMStockReport()
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "RmStockReport&rs:Command=Render&rs:Format=PDF";
            //string reportURL = url + "StockReport" ;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        public ActionResult GetRMDeliverReport(int requisitionId)
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "RMDeliveryReport&rs:Command=Render&rs:Format=PDF&RequisitionId=" + requisitionId;
            //string reportURL = url + "StockReport" ;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        public ActionResult GetRequisitionReport(int requisitionId)
        {
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = url + "RequisitionReport&rs:Command=Render&rs:Format=PDF&RequisitionId=" + requisitionId;
            //string reportURL = url + "StockReport" ;
            return File(client.DownloadData(reportURL), "application/pdf");
        }

        [HttpGet]

        public ActionResult GetDeliveryInvoiceReport(long OrderDeliverId, int companyId)
        {
            string reportName = string.Empty;
            if (companyId == 8)
            {
                reportName = "DeliveryInvoice";
            }

            //else if (companyId == 29)
            //{
            //    reportName = "GloryFeedDeliveryInvoice";
            //}
            //else if (companyId == (int)CompanyName.KrishibidFarmMachineryAndAutomobilesLimited)
            //{
            //    reportName = "KFMALDeliveryInvoice";
            //}
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = string.Format(url + "{0}&rs:Command=Render&rs:Format=PDF&OrderDeliverId={1}", reportName, OrderDeliverId);
            return File(client.DownloadData(reportURL), "application/pdf");
        }


        [HttpGet]

        public ActionResult FeedMYIncentivePolicy(int companyId)
        {
            string reportName = string.Empty;
            if (companyId == 8)
            {
                reportName = "FeedMYIncentivePolicy";
            }
            NetworkCredential nwc = new NetworkCredential(admin, password);
            WebClient client = new WebClient();
            client.Credentials = nwc;

KGERP/Views/HeadGLs/AccountingHeadList.cshtml
@using PagedList.Mvc;
@model KGERP.Service.ServiceModel.VMAccountHead
@using PagedList;
@{
    ViewBag.Title = "Accounting Head List";
    var message = TempData["message"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>

<section class="content-header">
    <h1>
        Accounting Head List
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">Accounting Head List</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="box-danger">

                    <div class="box">
                        <div class="box-danger">
                            <div class="box-header">

                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive">
                                    <table id="KgErpDataTable" class="table table-striped">
                                        <thead>
                                            <tr style="background-color:#32527B;color:#FFFFFF">
                                                <th>
                                                    SL
                                                </th>
                                                <td>
                                                    Chart 1
                                                </td>
                                                <td>
                                                    Chart 2
                                                </td>
                                                <td>
                                                    Chart 3
                                                </td>
                                                <td>
                                                    Chart 4
                                                </td>
                                                <td>
                                                    Chart 5
                                                </td>
                                                <td>
                                                    Accounting Head
                                                </td>
                                            </tr>
                                        </thead>
                                        @{int sl = 0;
                                        }
                                        <tbody>
                                            @foreach (var item in Model.DataList)
                                            {
                                                <tr>
                                                    <td>
                                                        @(++sl)
                                                    </td>
                                                    <td>
                                                        @item.Head1Name
                                                    </td>
                                                    <td>
                                                        @item.Head2Name
                                                    </td>
                                                    <td>
                                                        @item.Head3Name
                                                    </td>
                                                    <td>
                                                        @item.Head4Name
                                                    </td>
                                                    <td>
                                                        @item.Head5Name
                                                    </td>
                                                    <td>
                                                        @item.GLName
                                                    </td>

                                                </tr>

                                            }
                                        </tbody>

                                    </table>
                                </div>




                            </div>
                            <div class="box-footer">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</section>



@section scripts {

    <script type="text/javascript">


        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();


        });

        function resetForm() {
            $('#commonCustomerformId')[0].reset();
            $('#btnSave').html("<i class='fa fa-edit'></i>&nbsp;Add");

        }

        function makeDeletable(id) {
            if (id !== null) {
                $('#customerIdDelete').val(id);
                $('#ActionIdDelete').val(3);

            }
        }

    </script>
}

KGERP/Views/HeadGLs/TreeView.cshtml
@model KGERP.ViewModel.HeadGLViewModel
@using System.Web.UI.WebControls
@using KGERP.TreeViewModel;

@{
    var message = TempData["successMessage"];
}
<div>
    <h3 style="color:darkblue;text-align:center">@Model.CompanyName</h3>
    <h4 class="text-center" style="border:1px solid #32527B; padding:0px; color:white; background-color:#32527B">
       Chart of Accounts - Treeview
    </h4>
   
    @using (Html.BeginForm("GetChartOfAccountReport", "Report", FormMethod.Get))
    {
        @Html.Hidden("companyId", new { companyId = Request.QueryString["companyId"] })
        @Html.Hidden("reportName", "ChartOfAccount")
        <input type="submit" name="EXPORT" value="EXPORT" class="btn btn-success pull-right" formtarget="_blank" />
        <select class="pull-right" style="color:#ffffff; background-color:#dd4b39;height:34px;font-size:15px" name="ReportType" id="ReportType">
            <option value="PDF">PDF</option>
            <option value="EXCEL">EXCEL</option>
            <option value="WORD">WORD</option>
        </select>
    }
    @*@using (Html.BeginForm("ProdReferenceGet", "Report", FormMethod.Get))
    {
        @Html.Hidden("companyId", new { companyId = 21 })
        @Html.Hidden("reportName", "ProdReference")
        <input type="submit" name="EXPORT" value="EXPORT" class="btn btn-success pull-right" formtarget="_blank" />
        <select class="pull-right" style="color:#ffffff; background-color:#dd4b39;height:34px;font-size:15px" name="ReportType" id="ReportType">
            <option value="PDF">PDF</option>
            <option value="EXCEL">EXCEL</option>
            <option value="WORD">WORD</option>
        </select>
    }*@
</div>

@*<link href="~/Scripts/TreeView/dist/themes/default/style.min.css" rel="stylesheet" />*@
<div class="form-body">
    <div>
        <input type="text" placeholder="Search for Chart of account..." autocomplete="off" class="form-control" id="searchCharts">
    </div>
    <div id="jstreeChartOfAccounts">
        @(Html.TreeView(Model.Head1s).EmptyContent("<b style='font-family:arial;color:#32527B'>General Ledger</b>")
                                                                                                                                                                          .Children(m => m.Head11)
                                                                                                                                                                          .HtmlAttributes(new { id = "tree" })
                                                                                                                                                                      .ChildrenHtmlAttributes(new { @class = "subItem" })
                                                                                                                                                                          .ItemText(m => m.AccCode)
                                                                                                                                                                          .ItemTemplate(
                                                                                                                                                        @<text>
                                                                                                                                                            <a href="#" onclick='getChartOfAccount("@item.Id","@item.LayerNo","@item.AccCode","@item.AccName")' title="Create New Child Head or Update Existing" desc="@item.AccName"><span style="font-family:Arial;font-weight:bold;color:#32527B">@(item.AccCode + "-" + item.AccName)</span></a>
                                                                                                                                                        </text>)
        )
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#28845B;color:#ffffff !important">
                <b class="modal-title" id="exampleModalLongTitle">Selection Window</b>
                <a href="@Url.Action("TreeView","HeadGLs",new { companyId=Model.Head1s.First().CompanyId})" class="close" aria-label="Close" title="Close">
                    <span aria-hidden="true">&times;</span>
                </a>
            </div>
            <div class="modal-body" style="height:83px">
                ...
            </div>
            @*<div class="modal-footer">

                </div>*@
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="createEditAccountHeadModal" tabindex="-1" role="dialog" aria-labelledby="createEditAccountHeadTitle" aria-hidden="true" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#32527B;color:#ffffff">
                <b class="modal-title" id="createEditAccountHeadTitle">Selection Window form _selectionWindow Pertial view</b>
                <a href="@Url.Action("TreeView","HeadGLs",new { companyId=Model.Head1s.First().CompanyId})" class="close pull-right" aria-label="Close" title="Close">
                    <span aria-hidden="true">&times;</span>
                </a>
                <span class="pull-right" id="spanStatus"></span>

            </div>
            <div class="create-edit-accont-head-modal-body" style="height:200px;margin-top:5px">
                ...
            </div>
            @*<div class="modal-footer">

                </div>*@
        </div>
    </div>
</div>





@section scripts
{
    <script>
    var message = '@message';
    //if(message){
    //    alert(message);
    //}

        $(function () {
            var selectedData;
            $('#jstreeChartOfAccounts').jstree({
                "core": {
                    "multiple": true,
                    "check_callback": false,
                    'themes': {
                        "responsive": true,
                        'variant': 'medium',
                        'stripes': false,
                        'dots': true,
                    }
                },
                "plugins": ["search", "state"],
                "search": {
                    "case_sensitive": false,
                    "show_only_matches": true
                },
                "types": {
                    "default": {
                        "icon": "glyphicon glyphicon-minus-sign"
                    },
                    "demo": {
                        "icon": "glyphicon glyphicon-plus-sign"
                    }

                }
            });
        });

        $(document).ready(function () {
            $("#searchCharts").keyup(function () {
                var searchString = $(this).val();
                //console.log(searchString);
                $('#jstreeChartOfAccounts').jstree('search', searchString);
            });
        });


        function getChartOfAccount(accountHeadId, layerNo, accCode, accName) {

            $.ajax({
                url: '/HeadGLs/GetSelectionWindow?accountHeadId=' + accountHeadId + '&layerNo=' + layerNo + "&accCode=" + accCode + "&accName=" + accName + "",
                type: "GET",
                async: true,
                processData: false,
                cache: false,
                success: function (data) {
                    $('#exampleModalLongTitle').html("<style='font:bold'>" + accCode + "-" + accName + "</style>");
                    console.log(data);
                    $(".modal-body").html(data);
                    $("#exampleModalLong").modal({
                        show: true,
                        backdrop: 'static',
                        keyboard: false

                    });

                },
                error: function (xhr) {
                    alert('error');
                }
            });
        }
    </script>
}

KGERP/Views/HeadGLs/_childHeadCreateOrEdit.cshtml
@model KGERP.Service.ServiceModel.AccountHeadProcessModel



@using (Html.BeginForm("Create", "HeadGLs", FormMethod.Post, new { @novalidate = "novalidate" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CompanyId)
    @Html.HiddenFor(model => model.Status)
    @Html.HiddenFor(model => model.ParentId)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.LayerNo)

<div class="form-horizontal">
    @*<h4>@("[Parent Head] : [" + Model.ParentAccountName + "]") </h4>
        <hr style="border-color:#006747; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />*@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.AccCode, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.AccCode, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.AccName, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.AccName, new { htmlAttributes = new { @class = "form-control", @id = "txtAccountCode" } })
                @Html.ValidationMessageFor(model => model.AccName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.OrderNo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col-md-6">
      
    </div>

    <div class="col-md-6">
        <input type="submit"  style="margin-left:8px" class="btn btn-success pull-right" value="@Model.ButtonName" />
        <a href="@Url.Action("TreeView","HeadGLs",new { companyId=Model.CompanyId})" class="btn btn-danger pull-right">Close</a>


    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")



    <script type="text/javascript">
    </script>
}